CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar
);

CREATE TABLE "todo_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "content" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "is_deleted" bool DEFAULT false
);

CREATE INDEX ON "users" ("email");

CREATE INDEX ON "todo_items" ("user_id");

ALTER TABLE "todo_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
